FROM opensuse/leap

RUN zypper --non-interactive install \
  bind-utils \
  curl \
  docker \
  gcc \
  git \
  gzip \
  jq \
  make \
  python \
  python2-pip \
  python3 \
  python3-pip \
  ruby \
  unzip \
  vim \
  wget \
  zip
RUN pip install --upgrade pip
RUN pip install yq
