resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: teliaoss/github-pr-resource
- name: status
  type: docker-image
  source:
    repository: resource/github-status
    tag: release

resources:
- name: pr-src
  type: pull-request
  webhook_token: ((github.webhook-token))
  source:
    repository: ((pr-repo))
    access_token: ((github.access-token))
- name: status
  type: status
  source:
    access_token: ((github.access-token))
    repo: ((pr-repo))
- name: ci
  type: git
  source:
    uri: ((ci-repo))
    branch: ((ci-branch))
- name: docker.cf-operator-ci
  type: docker-image
  source:
    repository: ((docker-organization))/((docker-repo))
    username: ((dockerhub.username))
    password: ((dockerhub.password))
- name: s3.env-dump
  type: s3
  source:
    access_key_id: ((s3.accessKey))
    secret_access_key: ((s3.secretKey))
    bucket: ((s3.bucketName))
    regexp: env_dumps/env_dump-(.*).tar.gz


jobs:
- name: vet
  serial: true
  plan:
  - aggregate:
    - get: ci
    - get: pr-src
      trigger: true
  - task: vendorize-src
    file: ci/pipelines/cf-operator-check/tasks/vendorize-src.yml
  - put: status
    params:
      context: vet
      description: go vet check
      path: pr-src
      state: pending
  - do:
    - task: vet
      file: ci/pipelines/tasks/vet.yml
    on_failure:
      put: status
      params:
        context: vet
        description: go vet check
        path: pr-src
        state: failure
    on_success:
      put: status
      params:
        context: vet
        description: go vet check
        path: pr-src
        state: success

- name: lint
  serial: true
  plan:
  - aggregate:
    - get: ci
    - get: pr-src
      trigger: true
  - task: vendorize-src
    file: ci/pipelines/cf-operator-check/tasks/vendorize-src.yml
  - put: status
    params:
      context: lint
      description: lint check
      path: pr-src
      state: pending
  - do:
    - task: lint
      file: ci/pipelines/tasks/lint.yml
    on_failure:
      put: status
      params:
        context: lint
        description: go lint check
        path: pr-src
        state: failure
    on_success:
      put: status
      params:
        context: lint
        description: go lint check
        path: pr-src
        state: success

- name: test
  serial: true
  plan:
  - aggregate:
    - get: ci
    - get: pr-src
      trigger: true
  - task: vendorize-src
    file: ci/pipelines/cf-operator-check/tasks/vendorize-src.yml

  - aggregate:
    - put: status
      params:
        context: build
        description: go build check
        path: pr-src
        state: pending
    - put: status
      params:
        context: test
        description: go test check
        path: pr-src
        state: pending

  - do:
    - task: build
      file: ci/pipelines/tasks/build.yml
    - put: docker.cf-operator-ci
      params:
        build: src
        build_args:
          GO111MODULE: 'off'
        tag: docker/tag
    on_failure:
      put: status
      params:
        context: build
        description: go build check
        path: pr-src
        state: failure
    on_success:
      put: status
      params:
        context: build
        description: go build check
        path: pr-src
        state: success

  - do:
    - task: test
      file: ci/pipelines/tasks/test.yml
    - task: test-integration
      params:
        ibmcloud_apikey: ((ibmcloud.key-value))
        ibmcloud_server: ((ibmcloud.server))
        ibmcloud_region: ((ibmcloud.region))
        ibmcloud_cluster: ((ibmcloud.cluster-dino))
        ssh_server_ip: ((ssh-server.ip))
        ssh_server_user: ((ssh-server.user))
        ssh_server_key: ((ssh-server.key))
        OPERATOR_TEST_STORAGE_CLASS: ((storageclass))
        DOCKER_IMAGE_REPOSITORY: ((docker-repo))
        NODES: 6
      file: ci/pipelines/tasks/test-integration.yml
    - task: test-helm-e2e
      params:
        ibmcloud_apikey: ((ibmcloud.key-value))
        ibmcloud_server: ((ibmcloud.server))
        ibmcloud_region: ((ibmcloud.region))
        ibmcloud_cluster: ((ibmcloud.cluster-dino))
        ssh_server_ip: ((ssh-server.ip))
        ssh_server_user: ((ssh-server.user))
        ssh_server_key: ((ssh-server.key))
        OPERATOR_TEST_STORAGE_CLASS: ((storageclass))
        DOCKER_IMAGE_REPOSITORY: ((docker-candidate-repo))
      file: ci/pipelines/tasks/test-helm-e2e.yml
    on_failure:
      do:
      - put: s3.env-dump
        params:
          file: env_dumps/env_dump-*.tar.gz
          acl: public-read
      - put: status
        params:
          context: test
          description: go test check
          path: pr-src
          state: failure
    on_success:
      put: status
      params:
        context: test
        description: go test check
        path: pr-src
        state: success
