# This pipeline will setup the build for all the cf_deployment_releases specified below.

<%
cf_deployment_tags = %w(v7.11.0 v8.0.0 v8.1.0 v9.0.0 v9.2.0)
%>

resources:
- name: ci
  type: git
  tags: [containerization]
  source:
    uri: ((ci-repo))
    branch: ((ci-branch))
- name: docker-image-resource
  type: git
  tags: [containerization]
  source:
    uri: ((docker-image-resource-repo))
    branch: ((docker-image-resource-branch))
<% cf_deployment_tags.each do |cf_deployment_tag| %>
- name: cf-deployment-<%= cf_deployment_tag %>
  type: git
  tags: [containerization]
  source:
    uri: ((cf-deployment-repo))
    branch: ((cf-deployment-branch))
    tag_filter: <%= cf_deployment_tag %>
<% end %>
- name: s3.fissile-linux
  type: s3
  tags: [containerization]
  source:
    bucket: ((s3-bucket))
    private: true
    regexp: fissile/develop/fissile-(.*)\.tgz
- name: s3.fissile-stemcell-opensuse-version
  type: s3
  tags: [containerization]
  source:
    bucket: ((versions-s3-bucket))
    access_key_id: ((s3.accessKey))
    secret_access_key: ((s3.secretKey))
    versioned_file: fissile-stemcell-versions/fissile-stemcell-opensuse-version

jobs:
<% cf_deployment_tags.each do |cf_deployment_tag| %>
- name: build-<%= cf_deployment_tag %>
  plan:
  - aggregate:
    - get: ci
    - get: docker-image-resource
    - get: cf-deployment-<%= cf_deployment_tag %>
    - get: s3.fissile-stemcell-opensuse-version
      trigger: true
    - get: s3.fissile-linux
      trigger: true
  - do:
    - task: build
      privileged: true
      input_mapping:
        s3.stemcell-version: s3.fissile-stemcell-opensuse-version
        cf-deployment: cf-deployment-<%= cf_deployment_tag %>
      tags: [containerization]
      params:
        STEMCELL_OS: ((stemcell-os))
        STEMCELL_REPOSITORY: ((stemcell-repository))
        CF_DEPLOYMENT_YAML: ((cf-deployment-yaml))
        DOCKER_ORGANIZATION: ((docker-organization))
        DOCKER_TEAM_USERNAME: ((dockerhub.username))
        DOCKER_TEAM_PASSWORD_RW: ((dockerhub.password))
      file: ci/pipelines/release-images-cf-deployment/tasks/build.yml
<% end %>
